config/routes.rb
SemiStatic::Engine.routes.draw do
  %w( 404 422 500 ).each do |code|
    get code, :to => "errors#show", :code => code
  end

  # Set the root of the website to the Site controller
  root :action => 'show', :via => :get, :controller => 'site'
  # And also define home_path as the root
  get '/' => 'site#show', :as => 'home'

  #
  # For Tags that put their name in the url ("context_urls").
  #
  # For example if the Tag was called 'blog', then rather than the standard:
  #   /entries/278-my-great-page
  # we would have:
  #   /blog/278-my-great-page
  # The controller would redirect /entries/278-my-great-page to /blog/278-my-great-page
  #
  # We only provide GET routes, which means that edit/update of the Entry with
  # POST/PUT/PATCH will not work. But since this is only ever done in the admin
  # dashboard we choose to deal this by hand (see form_for in entries/_form.html.haml)
  #
  if ActiveRecord::Base.connection.table_exists? 'semi_static_tags'
    SemiStatic::Tag.with_context_urls.collect{|t| t.name.parameterize}.each do |tn|
      # Shortened routes for SemiStatic Tags, the Tag name is in the URL
      # and needs to be passed to the controller as the :slug parameter
      get "/#{tn}", to: 'tags#show', :slug => "#{tn}"

      # Create routes for tag that create their own URL
      get "/#{tn}/:id" => 'entries#show'
    end
  end

  if SemiStatic::Engine.config.tag_paths.present?
    #
    # For prettier Tag URLs. Without this your URL for a Tag index page call 'blog' would be
    #   /tag/blog
    # With this you can set the Tag URL's. By default in english it is "features", the URL above would no be
    #   /features/blog
    # see config/initializers/semi_static.rb
    #
    # We create the routes for all the different locales while the "features_path" helper creates the
    # correct url in the webpage itself depending on the locale. Currently that means that all
    # the locale versions of the website will respond to all the urls in SemiStatic::Engine.config.tag_paths which
    # is probably not optimal, so we raise error in TagsController
    SemiStatic::Engine.config.tag_paths.keys.each do |l|
      get "/#{SemiStatic::Engine.config.tag_paths[l]}/:slug" => 'tags#show', :as => "#{l}_features"
    end
  else

    get '/news' => 'tags#show', :slug => 'news'
  end

  # In case the Entry is not served by a Tag with a context_url
  resources :entries, :only => :show
  get '/search' => 'entries#search', :as => 'search'

  resources :contacts
  get '/contact', :to => redirect('/contacts/new')
  get '/contacts/registration' => 'contacts#new', :as => 'new_registration'

  resources :sitemaps, :only => :index

  # Public galleries path
  get "/gallery", :to => 'galleries#index', :as => 'public_galleries'

  get "/order/:id" => "carts#show", :as => 'shopping-cart'

  # Public documents paths
  get "/documents" => 'documents#index', :as => 'documents'
  get "/documents/index" => 'documents#index'
  get "/documents/:squeeze_id/:token" => 'documents#show', :as => 'document'

  resources :squeezes do
    resources :page_attrs, :except => :index
  end

  ###################################################################################
  #
  # SemiStatic scoped routes below
  #

  scope 'semi-static' do
    delete 'entries/:id' => 'entries#destroy', :as => 'delete_entry'
    resources :entries, :except => :show do
      collection { get :search }
      resources :click_ads, :only => [:new, :create, :update]
      resources :seos, :only => [:new, :create, :update, :destroy]
      resources :products, :except => [:index, :show]
      resources :photos, :only => :index
      resources :comments, :except => :new
      resources :page_attrs, :except => :index
    end

    resources :fcols do
      resources :links, :except => :show
    end

    resources :seos do
      resources :hreflangs, :except => :show
    end

    resources :tags, :except => :show do
      resources :seos, :only => [:new, :create, :update, :destroy]
      resources :entries, :only => [:index]
      resources :page_attrs, :except => :index
    end

    # Catch all for the Tag route with slug when context_url is used etc
    #      get "/#{tn}", to: 'tags#show', :slug => "#{tn}"
    resources :tags, :only => :show, :param => :slug

    # The route /gallery is reserved to the pre-defined Gallery Tag which
    # displays the websites public photos selected from various SemiStatic
    # Galleries
    resources :galleries, :as => 'galleries'
    resources :photos do
      resources :seos, :only => [:new, :create, :update]
    end

    # For the orders and shopping carts, the carts index is actually
    # the orders but serviced by the orders controller. The cart is
    # actually the current_order, there is no ID for it, it's in the
    # session cookie, so the URL does not have and :id
    resource :cart, only: [:show, :edit, :update]
    resources :carts, only: [:index]
    resources :order_items, only: [:create, :update, :destroy]

    # Note the need to put provide the explict path, else the defined route with clash with the
    # contact_path routes outside of the semi-static scope
    resources :contacts, :path => 'contacts', :as => 'contacts', :only => [:show, :index, :destroy]

    resources :charges, :only => [:new, :create]

    resources :newsletters do
      resources :newsletter_deliveries, :only => :index
    end

    resources :squeezes do
      resources :page_attrs, :except => :index
    end

    resources :job_postings
    resources :events, :except => :show
    resources :sidebars
    resources :products
    resources :newsletter_deliveries, :only => :update
    resources :subscribers, :except => :show do
      resources :newsletter_deliveries, :only => :index
    end
    resources :subscriber_categories, :only => [:new, :create, :destroy]
    resources :banners
    resources :references
    resources :click_ads, :except => [:new, :create, :update]
    resources :seos, :except => [:new, :create, :update]
    resources :agreements
  end

  # For the payment processor (stripe.com)

  get "/semi-static/page-attributes/index" => 'page_attrs#index', :as => 'page_attrs'
  delete "/semi-static/page-attribute/:id" => 'page_attrs#destroy', :as => 'page_attr'
  get "/comments/index" => 'comments#index', :as => 'comments'


  # Special route, normally only used by the webserver to get CSRF tags
  get '/site/csrf_meta_tags' => 'site#csrf_meta_tags'

  get '/site/:content' => 'site#show', :as => 'site'

  get "site/show"




  get '/semi-static/dashboard' => 'dashboards#show', :as => 'semi_static_dashboard'

  # Most system cmd use update, even though they often are not posting anything
  put '/system' => "system#update"
  get '/system/show' => "system#show"
end

app/models/semi_static/agreement.rb
module SemiStatic
  class Agreement < ApplicationRecord
    
    has_and_belongs_to_many :contacts, :join_table => :semi_static_agreements_contacts

    scope :locale, -> (locale){where("locale = ?", locale.to_s)}
    scope :subscriber, -> {where(:add_to_subscribers => true)}

    before_update :readonly
    before_destroy :readonly

    def readonly
      #
      # Can only change the ticked_by_default or display attributes
      #
      unless self.contacts.empty? ||
        self.changed.size == 0 ||
        (self.changed.size == 1 && self.changed.include?('ticked_by_default')) ||
        (self.changed.size == 1 && self.changed.include?('display')) ||
        (self.changed.size == 2 && self.changed.include?('display') && self.changed.include?('ticked_by_default'))
 
        self.errors.add(:base, 'Cannot delete or edit this agreement in the way you have attempted, you must remove contacts first or unset only the display or ticked attributes')
        false
      end
    end

  end
end

app/models/semi_static/application_record.rb
module SemiStatic
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/semi_static/banner.rb
module SemiStatic
  class Banner < ApplicationRecord
    include Pages

    # 
    # For reference:
    #
    # attr_accessible :name, :tag_line, :img
    #

    has_many :entries
    has_many :tags
    has_many :newsletters

    THEME = {
      'tiles' => {:desktop => :desktop, :mobile => :mobile},
      'menu-right' => {:desktop => :desktopy500, :mobile => :mobile, :entry => :entry},
      'background-cover' => {:desktop => :desktopy500, :mobile => :mobile, :entry => :entry},
      'bannerless' => {:desktop => :desktopBig, :mobile => :mobileBig, :entry => :entry},
      'standard-2col-1col' => {:desktop => :desktop, :mobile => :mobile},
      'bannerette-2col-1col' => {:desktop => :bannerette, :mobile => :mobile},
      'elegant' => {:desktop => :desktopSmall, :mobile => :mobileSmall},
      'plain-3col' => {:desktop => :desktop, :mobile => :mobile},
      'parallax' => {:desktop => :parallax, :mobile => :parallax},
      'plain-big-banner-3col' => {:desktop => :desktopy500, :mobile => :mobiley500}
    }

    has_attached_file :img,
       :url => "/system/banners/:id/:style/:filename",
       :path => ":rails_root/public/system/banners/:id/:style/:filename",
       :styles => { :desktop=> "1500x300#",
                    :entry => "900x500#",
                    :mobile => "750x300#",
                    :backgroundx2 => "3200x>",
                    :background => "1600x>",
                    :parallax => "1000x>",
                    :desktopBg => "1400x>",
                    :tabletBg => "820x>",
                    :mobileBg => "580x>",
                    :bannerette => "1012x300#",
                    :desktopBig => "1400x350#",
                    :tabletBig => "820x350#",
                    :mobileBig => "580x350#",
                    :desktopSmall => "1000x150#",
                    :mobileSmall => "750x150#",
                    :desktopy500 => "1500x500>",
                    :mobiley500 => "750x500#" },
       :convert_options => { :desktop => "-strip -gravity Center -quality 80",
                             :entry => "-strip -gravity Center -quality 85" ,
                             :bannerette => "-strip -gravity Center -quality 80" ,
                             :header => "-strip -gravity Center -quality 75" ,
                             :parallax => "-strip -gravity Center -quality 75" ,
                             :background => "-strip -gravity Center -quality 70" ,
                             :backgroundx2 => "-strip -gravity Center -quality 30" ,
                             :desktopBg => "-strip -gravity Center -quality 70" ,
                             :tabletBg => "-strip -gravity Center -quality 70" ,
                             :mobileBg => "-strip -gravity Center -quality 70" ,
                             :desktopBig => "-strip -gravity Center -quality 70" ,
                             :tabletBig => "-strip -gravity Center -quality 70" ,
                             :mobileBig => "-strip -gravity Center -quality 70" ,
                             :desktopy500 => "-strip -gravity Center -quality 75" ,
                             :mobiley500 => "-strip -gravity Center -quality 75" }

    validates_attachment_content_type :img, :content_type => ['image/jpeg', 'image/png', 'image/gif']

    def img_url_for_theme(screen)
      img.url(THEME[SemiStatic::Engine.config.theme][screen])
    end

    def img_height(theme, screen)
      Paperclip::Geometry.from_file(Rails.root.to_s + '/public' + img(THEME[theme][screen])).height.to_i
    end
  end
end

app/models/semi_static/click_ad.rb
module SemiStatic
  class ClickAd < ApplicationRecord

    # For reference
    #
    # attr_accessible :client, :url

    belongs_to :entry, :optional => true
  end
end

app/models/semi_static/comment.rb
module SemiStatic
  class Comment < ApplicationRecord
    attr_accessor :captcha, :captcha_code

    belongs_to :entry

    validates_presence_of :email
    validates_presence_of :name
    validates_presence_of :body

    validate :check_captcha, :on => :create
    after_create :check_strategy

    #
    # TODO: Collect these automatically at initialisation from the file names.
    #
    CAPTCHA_CODES = [
      '0353', '2004', '2333', '5433', '6530', '6615', '6995', '7331', '7582', '7764', '7888', '7960'
    ]

    #
    # Thus is a very simple formula, you may want to make yours more complex
    # but in our experience spammers don't invest much time in figuring these
    # things out.
    #
    # FWIW the formula is reverse the order then subtract 2 from each digit, eg:
    # '7388' => '8837' => '6615' 
    #
    #
    def check_captcha
      if (captcha_code != captcha.reverse.split(//).collect{|n| (((n.to_i + 10) - 2).modulo(10)).to_s}.join)
        errors.add(:captcha, "Your numbers do not match the numbers in the image")
        false
      end
    end

    def check_strategy
      send_email
    end

    def send_email
      SemiStatic::CommentMailer.comment_notification(self).deliver
    end
  end
end

app/models/semi_static/contact.rb
module SemiStatic
  class Contact < ApplicationRecord

    attr_accessor :custom_params

    has_and_belongs_to_many :agreements, :join_table => :semi_static_agreements_contacts
    belongs_to :squeeze, :optional => true
  
    # TODO: The load order of the locales files stops us adding the correct message for this, its
    # needs to say 'Please provide either an email or telephone number'
    # validates_presence_of :telephone, :unless => :email?
    validates_format_of :email, :with => /.+@.+\..+/i, :allow_blank => true, :allow_nil => true
    validates_presence_of :email, :unless => :telephone?
    validate :spam_email?
  
    after_create :execute_strategy
    after_create :check_subscription

    default_scope { order(created_at: :desc) }

    STRATEGIES = { :message => 0, :registration => 1, :download => 2, :subscriber => 3, :application => 4}
    STRATEGY_CODES = STRATEGIES.invert
  
    def check_subscription
      unless self.email.blank? || self.agreements.subscriber.blank?
        if (s = SemiStatic::Subscriber.find_by_email(self.email)).blank?
          s = SemiStatic::Subscriber.create(:surname => surname, :name => name, :email => email, :telephone => telephone, :locale => locale)
        else
          attributes.each{|k,v| attributes.delete(k) if read_attribute(k).blank?}
          s.update_attributes(:name => s.name, :surname => s.surname, :telephone  => s.telephone, :locale => s.locale)
        end
        s.category = SemiStatic::SubscriberCategory.find_by_name('website')
        s.save
      end
    end

    def spam_email?
      if SemiStatic::Engine.config.contact_form_spam_email
        strs = SemiStatic::Engine.config.contact_form_spam_email.split(',')
        if strs.any?{|word| self.email.include?(word.strip)}
          self.errors.add(
            :base, 'This appears to be SPAM. Sorry, we cannot process this request, please send email to '+
              SemiStatic::Engine.config.info_email
          )
        end
      end
      if SemiStatic::Engine.config.contact_form_strict
        # Check for URL in name field
        if self.name&.match(/^http/) || self.surname&.match(/^http/)
          self.errors.add(
            :base, 'This appears to be a SPAM link. Sorry, we cannot process this request, please send email to '+
              SemiStatic::Engine.config.info_email
          )
        end
      end
    end

    def fullname
      [name, surname].join(' ')
    end
  
    def execute_strategy
      self.send('strat_' + (STRATEGY_CODES[strategy] || :message).to_s)
    end

    def strategy_sym
      STRATEGY_CODES[strategy].to_sym
    end

    # Stratgies - always prefixed with 'strat_'

    def strat_message
      SemiStatic::ContactMailer.contact_notification(self).deliver
    end

    def strat_registration
      SemiStatic::ContactMailer.contact_notification(self).deliver
    end

    def strat_subscriber
      SemiStatic::ContactMailer.contact_notification(self).deliver
    end

    def strat_download
      self.token = loop do
        random_token = SecureRandom.urlsafe_base64(nil, false)
        break random_token unless Contact.exists?(token: random_token)
      end
      self.reason ||= (self.squeeze && self.squeeze.title)
      self.save
      SemiStatic::DownloadMailer.download_instructions(self).deliver
    end
  end
end

app/models/semi_static/customer.rb
module SemiStatic
  class Customer < ApplicationRecord
    has_many :orders

    validates_presence_of :email, :name, :surname    
  end
end

app/models/semi_static/event.rb
module SemiStatic
  class Event < ApplicationRecord

    # For reference
    #
    # attr_accessible :name, :description, :location, :location_address, :tz, :door_time, :start_date, :end_date, :duration
    # attr_accessible :in_language, :typical_age_range
    # attr_accessible :offer_price, :offer_price_currency, :offer_max_price, :offer_min_price
    # attr_accessible :registration, :registration_url, :registration_text

    has_many :entries
    belongs_to :squeeze, :optional => true

    validates :name, presence: true

    #
    # The symbols as significant as defined by schema.org https://schema.org/EventAttendanceModeEnumeration
    #
    ATTENDANCE_MODE = {
      :OfflineEventAttendanceMode => 1,
      :OnlineEventAttendanceMode => 2,
      :MixedEventAttendanceMode => 3,
    }

    ATTENDANCE_MODE_IDS = ATTENDANCE_MODE.invert

    #
    # The symbols as significant as defined by schema.org https://schema.org/EventStatusType
    #
    STATUS = {
      :EventCancelled => 1,
      :EventMovedOnline => 2,
      :EventPostponed => 3,
      :EventRescheduled => 4,
      :EventScheduled => 5
    }
 
    STATUS_IDS = STATUS.invert

  end
end

app/views/semi_static/page_attrs/_edit.html.haml
.modal-header
  %h5= ['Editing page attribute for ', @page_attrable.raw_title].join
  <button type="button" class="close" data-dismiss="modal" aria-label="Close"> <span aria-hidden="true">&times;</span> </button>
.modal-body
  = render 'form'

app/views/semi_static/page_attrs/_form.html.haml
= form_for([@page_attrable, @page_attr]) do |f|
  - if @page_attr.errors.any?
    #error_explanation
      %h2= "#{pluralize(@page_attr.errors.count, "error")} prohibited this page attribute from being saved:"
      %ul
        - @page_attr.errors.full_messages.each do |msg|
          %li= msg

  = hidden_field_tag :return, @return
  %h5 Page Attribute
  .stacked-input-group
    = f.label :attr_key, 'Key', :class => 'input-group-text'
    = f.text_field :attr_key, :class => 'form-control'
  .stacked-input-group
    = f.label :attr_value, 'Value', :class => 'input-group-text'
    = f.text_field :attr_value, :class => 'form-control'

  .row
    .col-md-12.mt-3
      = f.submit 'Save', :class => 'btn btn-danger btn-block'

app/views/semi_static/page_attrs/_new.html.haml
.modal-header
  %h5= ['New page attribute for: ', @page_attrable.raw_title].join
  <button type="button" class="close" data-dismiss="modal" aria-label="Close"> <span aria-hidden="true">&times;</span> </button>
.modal-body
  = render 'form'

app/views/semi_static/page_attrs/edit.js.haml
!= "$(\".modal\").modal('hide');"
!= "$(\"#generalModal .modal-content\").html('#{escape_javascript(render :partial => 'semi_static/page_attrs/edit')}');"
!= "$(\"#generalModal\").modal();"

app/views/semi_static/page_attrs/index.html.haml
.app-title
  %h1
    %i.fa.fa-attrs.invert
    %span Page Attributes
  
.tile
  .tile-body
    .infobox#page_attribute_help
      %h5= 'Page Attribute Help'
      %p= 'Page Attributes are values that can be set for most pages on your website (Entry or Tag). The values are usually required by custom or semi-custom layouts to indicate where to collect information or what certain values should be.'
      %p= 'There are also some Page Attributes that have a general usage, currently:'
      .table-responsive
        %table.table.sortable.table-bordered.table-hover
          %thead
            %tr
              %th= 'Key'
              %th= 'Value'
              %th= 'Page Type'
              %th= 'Effect'
          %tbody
            %tr
              %td= 'socialSharesEntryId'
              %td= 'Entry ID'
              %td= 'Tag'
              %td= 'Display social shares for this Tag according to the Entry configuration given by the ID'
            %tr
              %td= 'useAltImageAsMeta'
              %td= '<any value>'
              %td= 'Entry'
              %td= 'Use the Entry alt/new image as the og_image META image. Warning: Alt image must be present'
            %tr
              %td= 'pagination'
              %td= 'Integer value'
              %td= 'Tag or Entry'
              %td= 'Set the paginated number of Entry summaries displayed (Tag) or the paginated number of links to other Entries in side bar (Entry)'
            %tr
              %td= 'imageStyle'
              %td= 'half, compressed, mini, thumb, bar, tile, small, panel, medium, twocol, wide, big'
              %td= 'Tag or Entry'
              %td= 'Overides the default Entry image style (size and compression)'
            %tr
              %td=' internalSearchKeywords'
              %td= 'Text string of keywords'
              %td= 'Entry'
              %td= 'Forces the keywords to be placed in the internal website search index'
            %tr
              %td=' sideBarMenuTagId'
              %td= 'Tag ID'
              %td= 'Tag'
              %td= 'Uses the Tag ID entries for the sidebar navigation menu - Depricated, use sideBarTagIds instead'
            %tr
              %td=' sideBarMenuTagIds'
              %td= 'One or more Comma seperated Tag IDs'
              %td= 'Tag or Entry'
              %td= 'Uses the Entries in the Tag IDs to build the sidebar navigation menu. '
            %tr
              %td=' sideBarMenuHash'
              %td= 'Hash of title, subtitles amd Entry IDs'
              %td= 'Tag or Entry'
              %td= 'Constructs a custom sidebar navigation menu with sub-section headers, each sub-section header is wrapped in a div with class semiStaticSubMenuHeader so that you can add styling. Example of hash format: {"This is the title" => {"Sub Menu 1" => [304, 332], "Sub 2" => [16, 17, 98]}}'
      
            %tr
              %td=' sideBarNavEntries'
              %td= 'Comma seperated string of Entry IDs'
              %td= 'Tag'
              %td= 'The Tag and all Entries in this Tag will use the IDs to construct the sidebar sub-navigation'
            %tr
              %td=' sideBarMaxNewsItems'
              %td= 'Numeric value'
              %td= 'Tag or Entry'
              %td= 'Maximum news items to display in sidebar'
            %tr
              %td=' disableTagLine'
              %td= '<any value>'
              %td= 'Predefined Tag: Home'
              %td= 'Stops display of Tag Line on Home Page'
            %tr
              %td=' disableSideBarSocial'
              %td= '<any value>'
              %td= 'Predefined Tag: Home'
              %td= 'Stops display of social links in sidebar of Home Page'
            %tr
              %td= 'disableBanner'
              %td= '<any value>'
              %td= 'Predefined Tag: Home'
              %td= 'Stops display of Home Page Banner image'
            %tr
              %td= 'slideMenuHtmlLink'
              %td= '<HTML>'
              %td= 'Predefined Tag: Home'
              %td= 'Inserts the given HTML into every slide menu (if theme supports), wrapped with a unsorted list (ul li) tag'
            %tr
              %td= 'entryClasses'
              %td= '<comma seperated string of CSS classes>'
              %td= 'Entry'
              %td= 'Add the CSS class(es) to the entry'
            %tr
              %td= 'disableSideBarNav'
              %td= '<any value>'
              %td= 'Tag or Entry'
              %td= 'Stops display of navigation menu in sidebar'
            %tr
              %td= 'youTubeVideoControls'
              %td= '1'
              %td= 'Entry'
              %td= 'If set to 1 then the You Tube video will have the controls overlay'
            %tr
              %td= 'youTubeVideoWidth'
              %td= 'Integer'
              %td= 'Entry'
              %td= 'Sets the width, in pixels, of a YouTube video used in this Entry'
            %tr
              %td= 'youTubeVideoHeight'
              %td= 'Integer'
              %td= 'Entry'
              %td= 'Sets the height, in pixels, of a YouTube video used in this Entry'
            %tr
              %td= 'youTubeVideoLoading'
              %td= 'String: \'eager\' or \'lazy\''
              %td= 'Entry'
              %td= 'Sets the loading attribute on the YouTube video used in this Entry'
            %tr
              %td= 'slideMenu'
              %td= '<text string> or blank'
              %td= 'Tag or Entry'
              %td= 'Force display of link to this Tag or Entry in "slide menu" - if theme supports slide menu. If used with an Entry then the Tag to which the Entry belongs must be sent to displayed in the menu. Entry title will be used if no text string is given'
            %tr
              %td= 'pageHasProducts'
              %td= 'true'
              %td= 'Entry'
              %td= 'A shopping cart will be automatically loaded by SemiStatic if the main Entry has an associated Product (and \'config.shopping_cart\' is set true in the SemiStatic initializer). However, setting this PageAttr will force the cart to be loaded even if no product is associated with the main Entry and that any element of the form <div id=\'SemiStaticCartId_x\' class=\'semiStaticCartButton\'>... will be replaced with a cart button to order Product with ID x'
            %tr
              %td= 'csrfFormAuth'
              %td= 'true'
              %td= 'Tag or Entry'
              %td= 'Causes the HTML form CSRF auth tokens to be updated on the static pages. This is needed for cached pages that have a PUT/POST action and thus need the CSRF auth tokento match the session, eg. login forms on a static page.'
            %tr
              %td= 'entryTitleClasses'
              %td= '<comma seperated string of CSS classes>'
              %td= 'Entry'
              %td= 'Add the CSS class(es) to the entry title. This will be the h1 on an Entry page or perhaps a h2 on a Tag index page'
            %tr
              %td= 'entryIconGalleryId'
              %td= 'Photo ID'
              %td= 'Entry'
              %td= 'Display an icon before, or to the left, of the entry Title. You can determin the icon size yourself by loading different image sizes and adjusting the CSS. However, the default is 64px by 64px.'
            %tr
              %td= 'alwaysAllowContentDisplay'
              %td= '<any value>'
              %td= 'Entry'
              %td= 'If a Tag has this Entry as its content source by setting its ID in Tag#EntryAsTagIndex but this Entry is "Admin Only" content because of its own Tag settings, then normally you will not be able to view this Entry. However, you can override this behavious be setting this attribute to any value. Careful, it is an override and could be dangerous if you do not know what you are doing.'
    .infomarker= 'Page Attibutes Help'
    .table-responsive.table.sortable.table-bordered.table-hover
      %table
        %thead
          %tr
            %th= 'Key'
            %th= 'Value'
            %th= 'Page'
            %th= 'Entry'
            %th= 'Tag'
            %th= 'Squeeze'
        
        %tbody
          - SemiStatic::PageAttr.all.each do |pa|
            %tr
              %td= pa.attr_key.to_s
              %td= pa.attr_value.to_s
              %td
                -if pa.page_attrable.nil?
                  = link_to image_tag('/assets/error.png', :title => 'Error: Cannot find page/entry association, click to delete'), pa, :method => :delete, :data => { :confirm => "Confirm delete of #{pa.attr_key.to_s}" }
                - else
                  - unless pa.page_attrable.kind_of?(SemiStatic::Squeeze)
                    = link_to construct_url(pa.page_attrable, pa.page_attrable.locale), construct_url(pa.page_attrable, pa.page_attrable.locale)
              %td.tick
                - if pa.page_attrable.kind_of?(SemiStatic::Entry)
                  = link_to image_tag('/assets/tick.png', :title => 'Entry'), edit_entry_path(pa.page_attrable.id)
              %td.tick
                - if pa.page_attrable.kind_of?(SemiStatic::Tag)
                  = link_to image_tag('/assets/tick.png', :title => 'Tag'), edit_tag_path(pa.page_attrable.id)
              %td.tick
                - if pa.page_attrable.kind_of?(SemiStatic::Squeeze)
                  = link_to image_tag('/assets/tick.png', :title => 'Tag'), edit_squeeze_path(pa.page_attrable.id)

app/views/semi_static/page_attrs/new.js.haml
!= "$(\".modal\").modal('hide');"
!= "$(\"#generalModal .modal-content\").html('#{escape_javascript(render :partial => 'semi_static/page_attrs/new')}');"
!= "$(\"#generalModal\").modal();"