config/routes.rb
SemiStatic::Engine.routes.draw do
  %w( 404 422 500 ).each do |code|
    get code, :to => "errors#show", :code => code
  end

  # Set the root of the website to the Site controller
  root :action => 'show', :via => :get, :controller => 'site'
  # And also define home_path as the root
  get '/' => 'site#show', :as => 'home'

  #
  # For Tags that put their name in the url ("context_urls").
  #
  # For example if the Tag was called 'blog', then rather than the standard:
  #   /entries/278-my-great-page
  # we would have:
  #   /blog/278-my-great-page
  # The controller would redirect /entries/278-my-great-page to /blog/278-my-great-page
  #
  # We only provide GET routes, which means that edit/update of the Entry with
  # POST/PUT/PATCH will not work. But since this is only ever done in the admin
  # dashboard we choose to deal this by hand (see form_for in entries/_form.html.haml)
  #
  if ActiveRecord::Base.connection.table_exists? 'semi_static_tags'
    SemiStatic::Tag.with_context_urls.collect{|t| t.name.parameterize}.each do |tn|
      # Shortened routes for SemiStatic Tags, the Tag name is in the URL
      # and needs to be passed to the controller as the :slug parameter
      get "/#{tn}", to: 'tags#show', :slug => "#{tn}"

      # Create routes for tag that create their own URL
      get "/#{tn}/:id" => 'entries#show'
    end
  end

  if SemiStatic::Engine.config.tag_paths.present?
    #
    # For prettier Tag URLs. Without this your URL for a Tag index page call 'blog' would be
    #   /tag/blog
    # With this you can set the Tag URL's. By default in english it is "features", the URL above would no be
    #   /features/blog
    # see config/initializers/semi_static.rb
    #
    # We create the routes for all the different locales while the "features_path" helper creates the
    # correct url in the webpage itself depending on the locale. Currently that means that all
    # the locale versions of the website will respond to all the urls in SemiStatic::Engine.config.tag_paths which
    # is probably not optimal, so we raise error in TagsController
    SemiStatic::Engine.config.tag_paths.keys.each do |l|
      get "/#{SemiStatic::Engine.config.tag_paths[l]}/:slug" => 'tags#show', :as => "#{l}_features"
    end
  else

    get '/news' => 'tags#show', :slug => 'news'
  end

  # In case the Entry is not served by a Tag with a context_url
  resources :entries, :only => :show
  get '/search' => 'entries#search', :as => 'search'

  resources :contacts
  get '/contact', :to => redirect('/contacts/new')
  get '/contacts/registration' => 'contacts#new', :as => 'new_registration'

  resources :sitemaps, :only => :index

  # Public galleries path
  get "/gallery", :to => 'galleries#index', :as => 'public_galleries'

  get "/order/:id" => "carts#show", :as => 'shopping-cart'

  # Public documents paths
  get "/documents" => 'documents#index', :as => 'documents'
  get "/documents/index" => 'documents#index'
  get "/documents/:squeeze_id/:token" => 'documents#show', :as => 'document'

  resources :squeezes do
    resources :page_attrs, :except => :index
  end

  ###################################################################################
  #
  # SemiStatic scoped routes below
  #

  scope 'semi-static' do
    delete 'entries/:id' => 'entries#destroy', :as => 'delete_entry'
    resources :entries, :except => :show do
      collection { get :search }
      resources :click_ads, :only => [:new, :create, :update]
      resources :seos, :only => [:new, :create, :update, :destroy]
      resources :products, :except => [:index, :show]
      resources :photos, :only => :index
      resources :comments, :except => :new
      resources :page_attrs, :except => :index
    end

    resources :fcols do
      resources :links, :except => :show
    end

    resources :seos do
      resources :hreflangs, :except => :show
    end

    resources :tags, :except => :show do
      resources :seos, :only => [:new, :create, :update, :destroy]
      resources :entries, :only => [:index]
      resources :page_attrs, :except => :index
    end

    # Catch all for the Tag route with slug when context_url is used etc
    #      get "/#{tn}", to: 'tags#show', :slug => "#{tn}"
    resources :tags, :only => :show, :param => :slug

    # The route /gallery is reserved to the pre-defined Gallery Tag which
    # displays the websites public photos selected from various SemiStatic
    # Galleries
    resources :galleries, :as => 'galleries'
    resources :photos do
      resources :seos, :only => [:new, :create, :update]
    end

    # For the orders and shopping carts, the carts index is actually
    # the orders but serviced by the orders controller. The cart is
    # actually the current_order, there is no ID for it, it's in the
    # session cookie, so the URL does not have and :id
    resource :cart, only: [:show, :edit, :update]
    resources :carts, only: [:index]
    resources :order_items, only: [:create, :update, :destroy]

    # Note the need to put provide the explict path, else the defined route with clash with the
    # contact_path routes outside of the semi-static scope
    resources :contacts, :path => 'contacts', :as => 'contacts', :only => [:show, :index, :destroy]

    resources :charges, :only => [:new, :create]

    resources :newsletters do
      resources :newsletter_deliveries, :only => :index
    end

    resources :squeezes do
      resources :page_attrs, :except => :index
    end

    resources :job_postings
    resources :events, :except => :show
    resources :sidebars
    resources :products
    resources :newsletter_deliveries, :only => :update
    resources :subscribers, :except => :show do
      resources :newsletter_deliveries, :only => :index
    end
    resources :subscriber_categories, :only => [:new, :create, :destroy]
    resources :banners
    resources :references
    resources :click_ads, :except => [:new, :create, :update]
    resources :seos, :except => [:new, :create, :update]
    resources :agreements
  end

  # For the payment processor (stripe.com)

  get "/semi-static/page-attributes/index" => 'page_attrs#index', :as => 'page_attrs'
  delete "/semi-static/page-attribute/:id" => 'page_attrs#destroy', :as => 'page_attr'
  get "/comments/index" => 'comments#index', :as => 'comments'


  # Special route, normally only used by the webserver to get CSRF tags
  get '/site/csrf_meta_tags' => 'site#csrf_meta_tags'

  get '/site/:content' => 'site#show', :as => 'site'

  get "site/show"




  get '/semi-static/dashboard' => 'dashboards#show', :as => 'semi_static_dashboard'

  # Most system cmd use update, even though they often are not posting anything
  put '/system' => "system#update"
  get '/system/show' => "system#show"
end

app/models/semi_static/agreement.rb
module SemiStatic
  class Agreement < ApplicationRecord
    
    has_and_belongs_to_many :contacts, :join_table => :semi_static_agreements_contacts

    scope :locale, -> (locale){where("locale = ?", locale.to_s)}
    scope :subscriber, -> {where(:add_to_subscribers => true)}

    before_update :readonly
    before_destroy :readonly

    def readonly
      #
      # Can only change the ticked_by_default or display attributes
      #
      unless self.contacts.empty? ||
        self.changed.size == 0 ||
        (self.changed.size == 1 && self.changed.include?('ticked_by_default')) ||
        (self.changed.size == 1 && self.changed.include?('display')) ||
        (self.changed.size == 2 && self.changed.include?('display') && self.changed.include?('ticked_by_default'))
 
        self.errors.add(:base, 'Cannot delete or edit this agreement in the way you have attempted, you must remove contacts first or unset only the display or ticked attributes')
        false
      end
    end

  end
end

app/models/semi_static/application_record.rb
module SemiStatic
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/semi_static/banner.rb
module SemiStatic
  class Banner < ApplicationRecord
    include Pages

    # 
    # For reference:
    #
    # attr_accessible :name, :tag_line, :img
    #

    has_many :entries
    has_many :tags
    has_many :newsletters

    THEME = {
      'tiles' => {:desktop => :desktop, :mobile => :mobile},
      'menu-right' => {:desktop => :desktopy500, :mobile => :mobile, :entry => :entry},
      'background-cover' => {:desktop => :desktopy500, :mobile => :mobile, :entry => :entry},
      'bannerless' => {:desktop => :desktopBig, :mobile => :mobileBig, :entry => :entry},
      'standard-2col-1col' => {:desktop => :desktop, :mobile => :mobile},
      'bannerette-2col-1col' => {:desktop => :bannerette, :mobile => :mobile},
      'elegant' => {:desktop => :desktopSmall, :mobile => :mobileSmall},
      'plain-3col' => {:desktop => :desktop, :mobile => :mobile},
      'parallax' => {:desktop => :parallax, :mobile => :parallax},
      'plain-big-banner-3col' => {:desktop => :desktopy500, :mobile => :mobiley500}
    }

    has_attached_file :img,
       :url => "/system/banners/:id/:style/:filename",
       :path => ":rails_root/public/system/banners/:id/:style/:filename",
       :styles => { :desktop=> "1500x300#",
                    :entry => "900x500#",
                    :mobile => "750x300#",
                    :backgroundx2 => "3200x>",
                    :background => "1600x>",
                    :parallax => "1000x>",
                    :desktopBg => "1400x>",
                    :tabletBg => "820x>",
                    :mobileBg => "580x>",
                    :bannerette => "1012x300#",
                    :desktopBig => "1400x350#",
                    :tabletBig => "820x350#",
                    :mobileBig => "580x350#",
                    :desktopSmall => "1000x150#",
                    :mobileSmall => "750x150#",
                    :desktopy500 => "1500x500>",
                    :mobiley500 => "750x500#" },
       :convert_options => { :desktop => "-strip -gravity Center -quality 80",
                             :entry => "-strip -gravity Center -quality 85" ,
                             :bannerette => "-strip -gravity Center -quality 80" ,
                             :header => "-strip -gravity Center -quality 75" ,
                             :parallax => "-strip -gravity Center -quality 75" ,
                             :background => "-strip -gravity Center -quality 70" ,
                             :backgroundx2 => "-strip -gravity Center -quality 30" ,
                             :desktopBg => "-strip -gravity Center -quality 70" ,
                             :tabletBg => "-strip -gravity Center -quality 70" ,
                             :mobileBg => "-strip -gravity Center -quality 70" ,
                             :desktopBig => "-strip -gravity Center -quality 70" ,
                             :tabletBig => "-strip -gravity Center -quality 70" ,
                             :mobileBig => "-strip -gravity Center -quality 70" ,
                             :desktopy500 => "-strip -gravity Center -quality 75" ,
                             :mobiley500 => "-strip -gravity Center -quality 75" }

    validates_attachment_content_type :img, :content_type => ['image/jpeg', 'image/png', 'image/gif']

    def img_url_for_theme(screen)
      img.url(THEME[SemiStatic::Engine.config.theme][screen])
    end

    def img_height(theme, screen)
      Paperclip::Geometry.from_file(Rails.root.to_s + '/public' + img(THEME[theme][screen])).height.to_i
    end
  end
end

app/models/semi_static/click_ad.rb
module SemiStatic
  class ClickAd < ApplicationRecord

    # For reference
    #
    # attr_accessible :client, :url

    belongs_to :entry, :optional => true
  end
end

app/models/semi_static/comment.rb
module SemiStatic
  class Comment < ApplicationRecord
    attr_accessor :captcha, :captcha_code

    belongs_to :entry

    validates_presence_of :email
    validates_presence_of :name
    validates_presence_of :body

    validate :check_captcha, :on => :create
    after_create :check_strategy

    #
    # TODO: Collect these automatically at initialisation from the file names.
    #
    CAPTCHA_CODES = [
      '0353', '2004', '2333', '5433', '6530', '6615', '6995', '7331', '7582', '7764', '7888', '7960'
    ]

    #
    # Thus is a very simple formula, you may want to make yours more complex
    # but in our experience spammers don't invest much time in figuring these
    # things out.
    #
    # FWIW the formula is reverse the order then subtract 2 from each digit, eg:
    # '7388' => '8837' => '6615' 
    #
    #
    def check_captcha
      if (captcha_code != captcha.reverse.split(//).collect{|n| (((n.to_i + 10) - 2).modulo(10)).to_s}.join)
        errors.add(:captcha, "Your numbers do not match the numbers in the image")
        false
      end
    end

    def check_strategy
      send_email
    end

    def send_email
      SemiStatic::CommentMailer.comment_notification(self).deliver
    end
  end
end

app/models/semi_static/contact.rb
module SemiStatic
  class Contact < ApplicationRecord

    attr_accessor :custom_params

    has_and_belongs_to_many :agreements, :join_table => :semi_static_agreements_contacts
    belongs_to :squeeze, :optional => true
  
    # TODO: The load order of the locales files stops us adding the correct message for this, its
    # needs to say 'Please provide either an email or telephone number'
    # validates_presence_of :telephone, :unless => :email?
    validates_format_of :email, :with => /.+@.+\..+/i, :allow_blank => true, :allow_nil => true
    validates_presence_of :email, :unless => :telephone?
    validate :spam_email?
  
    after_create :execute_strategy
    after_create :check_subscription

    default_scope { order(created_at: :desc) }

    STRATEGIES = { :message => 0, :registration => 1, :download => 2, :subscriber => 3, :application => 4}
    STRATEGY_CODES = STRATEGIES.invert
  
    def check_subscription
      unless self.email.blank? || self.agreements.subscriber.blank?
        if (s = SemiStatic::Subscriber.find_by_email(self.email)).blank?
          s = SemiStatic::Subscriber.create(:surname => surname, :name => name, :email => email, :telephone => telephone, :locale => locale)
        else
          attributes.each{|k,v| attributes.delete(k) if read_attribute(k).blank?}
          s.update_attributes(:name => s.name, :surname => s.surname, :telephone  => s.telephone, :locale => s.locale)
        end
        s.category = SemiStatic::SubscriberCategory.find_by_name('website')
        s.save
      end
    end

    def spam_email?
      if SemiStatic::Engine.config.contact_form_spam_email
        strs = SemiStatic::Engine.config.contact_form_spam_email.split(',')
        if strs.any?{|word| self.email.include?(word.strip)}
          self.errors.add(
            :base, 'This appears to be SPAM. Sorry, we cannot process this request, please send email to '+
              SemiStatic::Engine.config.info_email
          )
        end
      end
      if SemiStatic::Engine.config.contact_form_strict
        # Check for URL in name field
        if self.name&.match(/^http/) || self.surname&.match(/^http/)
          self.errors.add(
            :base, 'This appears to be a SPAM link. Sorry, we cannot process this request, please send email to '+
              SemiStatic::Engine.config.info_email
          )
        end
      end
    end

    def fullname
      [name, surname].join(' ')
    end
  
    def execute_strategy
      self.send('strat_' + (STRATEGY_CODES[strategy] || :message).to_s)
    end

    def strategy_sym
      STRATEGY_CODES[strategy].to_sym
    end

    # Stratgies - always prefixed with 'strat_'

    def strat_message
      SemiStatic::ContactMailer.contact_notification(self).deliver
    end

    def strat_registration
      SemiStatic::ContactMailer.contact_notification(self).deliver
    end

    def strat_subscriber
      SemiStatic::ContactMailer.contact_notification(self).deliver
    end

    def strat_download
      self.token = loop do
        random_token = SecureRandom.urlsafe_base64(nil, false)
        break random_token unless Contact.exists?(token: random_token)
      end
      self.reason ||= (self.squeeze && self.squeeze.title)
      self.save
      SemiStatic::DownloadMailer.download_instructions(self).deliver
    end
  end
end

app/models/semi_static/customer.rb
module SemiStatic
  class Customer < ApplicationRecord
    has_many :orders

    validates_presence_of :email, :name, :surname    
  end
end

app/models/semi_static/event.rb
module SemiStatic
  class Event < ApplicationRecord

    # For reference
    #
    # attr_accessible :name, :description, :location, :location_address, :tz, :door_time, :start_date, :end_date, :duration
    # attr_accessible :in_language, :typical_age_range
    # attr_accessible :offer_price, :offer_price_currency, :offer_max_price, :offer_min_price
    # attr_accessible :registration, :registration_url, :registration_text

    has_many :entries
    belongs_to :squeeze, :optional => true

    validates :name, presence: true

    #
    # The symbols as significant as defined by schema.org https://schema.org/EventAttendanceModeEnumeration
    #
    ATTENDANCE_MODE = {
      :OfflineEventAttendanceMode => 1,
      :OnlineEventAttendanceMode => 2,
      :MixedEventAttendanceMode => 3,
    }

    ATTENDANCE_MODE_IDS = ATTENDANCE_MODE.invert

    #
    # The symbols as significant as defined by schema.org https://schema.org/EventStatusType
    #
    STATUS = {
      :EventCancelled => 1,
      :EventMovedOnline => 2,
      :EventPostponed => 3,
      :EventRescheduled => 4,
      :EventScheduled => 5
    }
 
    STATUS_IDS = STATUS.invert

  end
end

app/views/semi_static/hreflangs/_edit.html.haml
.modal-header
  %h5= ['Editing hreflang tag for ', @hreflang.seo.seoable.raw_title, ' (', @hreflang.seo.seoable.class.to_s.split('::').last, ')'].join
  = modal_close
.modal-body
  = render 'form'

app/views/semi_static/hreflangs/_edit_hreflang_tags.html.haml
.modal-header
  %h5= "hreflang equiv for Tag: #{@tag.raw_title}"
  = modal_close
.modal-body
  %h5= ['locale:', @tag.locale.to_s].join(' ')
  = render 'hreflang_tags_form'

app/views/semi_static/hreflangs/_form.html.haml
= form_for([@seo, @hreflang]) do |f|
  - if @hreflang.errors.any?
    #error_explanation
      %h2= pluralize(@hreflang.errors.count, "error") + ' prohibited this hreflang from being saved:'
      %ul
        - @hreflang.errors.full_messages.each do |msg|
          %li= msg

  - if @seo.seoable.tag.href_equiv_tags.present?
    %table.table.sortable.table-bordered.table-hover
      %thead
        %tr
          %th
            %i.app-menu__icon.fa.fa-lang
          %th Title
          %th URL

      %tbody
        - @seo.seoable.tag.href_equiv_tags.each do |t|
          - t.entries.unmerged.each do |e|
            %tr.entry_select_options{:class => e.locale, :entry_id => "entry_id_#{e.id}"}
              %td= e.locale
              %td= e.title
              %td{:title => "#{SemiStatic::Engine.config.localeDomains[e.locale]}#{entry_path(e)}"}
                .btn.btn-primary.btn-sm.href_equiv_path{:data => {:locale => "#{e.locale}"}}
                  = "#{SemiStatic::Engine.config.localeDomains[e.locale]}#{entry_path(e)}"

  = labeled_selectbox(f, :locale, options_for_select((I18n.available_locales - [@seo.seoable.locale.to_sym]).collect{|l| [l, l]}, @hreflang.locale))
  = labeled_textfield(f, :href, 'URL')

  .row
    .col-md-12.mt-3
      = f.submit 'Save', :class => 'btn btn-primary'

app/views/semi_static/hreflangs/_hreflang_tags_form.html.haml
= form_for(@tag) do |f|
  - if @tag.errors.any?
    #error_explanation
      %h2= pluralize(@tag.errors.count, "error") + ' prohibited this Tag from being saved:'
      %ul
        - @tag.errors.full_messages.each do |msg|
          %li= msg

  - if @tag.href_equiv_tags.present?
    %table.table.sortable.table-bordered.table-hover
      %thead
        %tr
          %th 
            %i.app-menu__icon.fa.fa-lang
          %th  Name
          %th.right
            %i.app-menu__icon.fa.fa-delete
      %tbody
        - @tag.href_equiv_tags.each do |t|
          %tr
            %td= t.locale
            %td= t.raw_title
            %td
              = link_to tag_path(@tag, :params => {:href_equiv_tag_ids => (@tag.href_equiv_tag_ids - [t.id.to_i])}), :method => :put, :return => edit_tag_path(@tag) do
                %i.app-menu__icon.fa.fa-delete

  .input-group-prepend
    %span.input-group-text hreflang equiv Tag
    = select_tag :href_lang_tag, options_for_select(@tag.hreflang_tag_options.collect{|t| ["#{t.locale}: ##{t.id}: #{t.title}", t.id]}.prepend(["- None -", nil])), {:class => 'form-control'}
  
  .row
    .col-md-12.mt-3
      = f.submit 'Save', :class => 'btn btn-primary'

app/views/semi_static/hreflangs/_new.html.haml
.modal-header
  %h5= ['New hreflang tag for ', @hreflang.seo.seoable.raw_title, ' (', @hreflang.seo.seoable.class.to_s.split('::').last, ')'].join
  = modal_close
.modal-body
  - if @hreflang.siblings.present?
    %h5 Current hreflang
    .table-responsive
      %table.table.table-bordered.table-dense
        - @hreflang.siblings.each do |href|
          %tr
            %td= href.locale.to_s
            %td= link_to href.href, href.href
            %td.tick{:title => "Edit hreflang tag"}
              = link_to edit_seo_hreflang_path(@hreflang.seo, href, :return => seos_path), :remote => true do
                %i.app-menu__icon.fa.fa-edit
            %td.tick
              = link_to seo_hreflang_path(@hreflang.seo, href), :method => :delete, :data => { :confirm => 'Are you sure?' } do
                %i.app-menu__icon.fa.fa-delete


  %h5 New hreflang
  = render 'form'

app/views/semi_static/hreflangs/edit.html.erb
<h1>Editing hreflang</h1>

<%= render 'form' %>

<%= link_to 'Show', @hreflang %> |
<%= link_to 'Back', hreflangs_path %>

app/views/semi_static/hreflangs/edit.js.haml
!= "$(\"#generalModal .modal-content\").html('#{escape_javascript(render :partial => @html_template)}');"
!= "$(\"#generalModal .modal-dialog\").addClass('modal-lg').modal();"
!= "$(\"#generalModal\").modal();"

app/views/semi_static/hreflangs/index.html.erb
<h1>Listing hreflangs</h1>

<table>
  <tr>
    <th>Locale</th>
    <th>Href</th>
    <th>Seo</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @hreflangs.each do |hreflang| %>
  <tr>
    <td><%= hreflang.locale %></td>
    <td><%= hreflang.href %></td>
    <td><%= hreflang.seo_id %></td>
    <td><%= link_to 'Show', hreflang %></td>
    <td><%= link_to 'Edit', edit_hreflang_path(hreflang) %></td>
    <td><%= link_to 'Destroy', hreflang, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Hreflang', new_hreflang_path %>

app/views/semi_static/hreflangs/new.html.erb
<h1>New hreflang</h1>

<%= render 'form' %>

<%= link_to 'Back', hreflangs_path %>

app/views/semi_static/hreflangs/new.js.haml
!= "$(\".modal\").modal('hide');"
!= "$(\"#generalModal .modal-content\").html('#{escape_javascript(render :partial => 'semi_static/hreflangs/new')}');"
!= "$(\"#generalModal .modal-dialog\").addClass('modal-lg').modal();"
!= "$(\"#generalModal\").modal();"

:plain
  function fill_url_input(){
    document.getElementById('hreflang_href').value = this.innerHTML;
    document.getElementById('hreflang_locale').value = this.dataset.locale;
    document.getElementById('hreflang_locale').scrollIntoView();
  }
  
  var elements = document.querySelectorAll('.href_equiv_path');
  Array.prototype.forEach.call(elements, function(el, i){
    el.addEventListener('click', fill_url_input); 
  });